version: 2
jobs: # we now have TWO jobs, so that a workflow can coordinate them!
  one: # This is our first job.
    docker: # it uses the docker executor
      - image: arm32v7/ubuntu:latest # specifically, a docker image with ruby 2.4.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout # this pulls code down from GitHub
      - run: cd openjdk-in-termux # This prints "A first hello" to stdout.
      - run: bash install.sh # a command telling the job to "sleep" for 25 seconds.
# Under the workflows: map, we can coordinate our two jobs, defined above.
workflows:
  version: 2
  Installing_java: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - one